# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:05:09+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query

from models import (
    ApiCatalogSystemPubFacetsCategoryCategoryIdGetResponse,
    ApiCatalogSystemPubFacetsSearchTermGetResponse,
    ApiCatalogSystemPubProductsCrosssellingWhoboughtalsoboughtProductIdGetResponse,
    ApiCatalogSystemPubProductsCrosssellingWhosawalsoboughtProductIdGetResponse,
    ApiCatalogSystemPubProductsCrosssellingWhosawalsosawProductIdGetResponse,
    ApiCatalogSystemPubProductsOffersProductIdGetResponse,
    ApiCatalogSystemPubProductsOffersProductIdSkuSkuIdGetResponse,
    ApiCatalogSystemPubProductsSearchGetResponse,
    ApiCatalogSystemPubProductsSearchProductTextLinkPGetResponse,
    ApiCatalogSystemPubProductsSearchSearchGetResponse,
    BuscaautocompleteGetResponse,
)

app = MCPProxy(
    contact={},
    description="\r\n> Check the new [Search onboarding guide](https://developers.vtex.com/vtex-rest-api/docs/search-onboarding). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Search and is organized by focusing on the developer's journey.\r\n\r\nThis API lets you search and sort products in the Catalog using Fulltext, Category and Brand search terms. \r\n\r\nRetrieve product data to create custom searches and product shelves.",
    title='Legacy Search API',
    version='1.0',
    servers=[
        {'url': 'https://vtex.local'},
        {
            'description': 'VTEX server url',
            'url': 'https://{accountName}.{environment}.com.br',
            'variables': {
                'accountName': {
                    'default': '{accountName}',
                    'description': 'Name of the VTEX account. Used as part of the URL',
                },
                'environment': {
                    'default': '{environment}',
                    'description': 'Environment to use. Used as part of the URL.',
                },
            },
        },
    ],
)


@app.get(
    '/api/catalog_system/pub/facets/category/{categoryId}',
    description=""" Retrieves the names and IDs of the categories facets. 
>⚠️ This endpoint returns a maximum of 50 items per response, so the difference between `_from` and `_to` should not exceed this number. The result order is descending, from the highest product ID to the lowest.

## Response body example:

```json
[
	[
    {
      "Name":"Tamanho Global",
      "Id":45
		},
		{
      "Name":"Percentuals",
      "Id":25
		}
	]
]
``` """,
    tags=['category_facet_retrieval'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def get_api_catalog_system_pub_facets_category__category_id(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    category_id: str = Path(..., alias='categoryId'),
    field_from: Optional[str] = Query(None, alias='_from'),
    field_to: Optional[str] = Query(None, alias='_to'),
):
    """
    Get Category Facets
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/facets/search/{term}',
    description=""" Retrieves products by store facets. 
>⚠️ This endpoint returns a maximum of 50 items per response, so the difference between `_from` and `_to` should not exceed this number. The result order is descending, from the highest product ID to the lowest.

## Response body example:

```json
{
	"Departments": [
  	{
    	"Quantity": 2,
      "Position": null,
      "Name": "Beers Beers Mesmo",
      "Link": "/Beers-Beers-Mesmo/1?map=c,b",
      "LinkEncoded": "/Beers-Beers-Mesmo/1?map=c,b",
      "Map": "c",
      "Value": "Beers-Beers-Mesmo"
     },
     {
     	"Quantity": 2,
      "Position": null,
      "Name": "Merch Integration Category ||",
      "Link": "/Merch-Integration-Category-||/1?map=c,b",
      "LinkEncoded": "/Merch-Integration-Category-%7C%7C/1?map=c,b",
      "Map": "c",
      "Value": "Merch-Integration-Category-||"
     },
     {
      "Quantity": 1,
      "Position": null,
      "Name": "Jogos",
      "Link": "/Jogos/1?map=c,b",
      "LinkEncoded": "/Jogos/1?map=c,b",
      "Map": "c",
      "Value": "Jogos"
     },
     {
      "Quantity": 3,
      "Position": null,
      "Name": "189",
      "Link": "/189/1?map=c,b",
      "LinkEncoded": "/189/1?map=c,b",
      "Map": "c",
      "Value": "189"
     },
     {
      "Quantity": 1,
      "Position": null,
      "Name": "Tests",
      "Link": "/Tests/1?map=c,b",
      "LinkEncoded": "/Tests/1?map=c,b",
      "Map": "c",
      "Value": "Tests"
     },
     {
      "Quantity": 1,
      "Position": null,
      "Name": "Accessories",
      "Link": "/Accessories/1?map=c,b",
      "LinkEncoded": "/Accessories/1?map=c,b",
      "Map": "c",
      "Value": "Accessories"
     },
     {
      "Quantity": 2,
      "Position": null,
      "Name": "Bars",
      "Link": "/Bars/1?map=c,b",
      "LinkEncoded": "/Bars/1?map=c,b",
      "Map": "c",
      "Value": "Bars"
     },
     {
      "Quantity": 5,
      "Position": null,
      "Name": "Categoria Teste Timeout",
      "Link": "/Categoria-Teste-Timeout/1?map=c,b",
      "LinkEncoded": "/Categoria-Teste-Timeout/1?map=c,b",
      "Map": "c",
      "Value": "Categoria-Teste-Timeout"
     }
    ],
    "Brands": [
     {
      "Quantity": 2,
      "Position": null,
      "Name": "Merch XP",
      "Link": "/1/1234600/1/Merch-XP?map=c,c,b,b",
      "LinkEncoded": "/1/1234600/1/Merch-XP?map=c,c,b,b",
      "Map": "b",
      "Value": "Merch-XP"
     },
     {
      "Quantity": 2,
      "Position": null,
      "Name": "Zé",
      "Link": "/1/1234600/1/Ze?map=c,c,b,b",
      "LinkEncoded": "/1/1234600/1/Ze?map=c,c,b,b",
      "Map": "b",
      "Value": "Ze"
     },
     {
      "Quantity": 1,
      "Position": null,
      "Name": "Odin",
      "Link": "/1/1234600/1/Odin?map=c,c,b,b",
      "LinkEncoded": "/1/1234600/1/Odin?map=c,c,b,b",
      "Map": "b",
      "Value": "Odin"
     },
     {
      "Quantity": 2,
      "Position": null,
      "Name": "Hoegaarden",
      "Link": "/1/1234600/1/Hoegaarden?map=c,c,b,b",
      "LinkEncoded": "/1/1234600/1/Hoegaarden?map=c,c,b,b",
      "Map": "b",
      "Value": "Hoegaarden"
     },
     {
      "Quantity": 1,
      "Position": null,
      "Name": "Teste marcas",
      "Link": "/1/1234600/1/Teste-marcas?map=c,c,b,b",
      "LinkEncoded": "/1/1234600/1/Teste-marcas?map=c,c,b,b",
      "Map": "b",
      "Value": "Teste-marcas"
     },
     {
       "Quantity": 1,
       "Position": null,
       "Name": "Bitmap Bureau",
       "Link": "/1/1234600/1/Bitmap-Bureau?map=c,c,b,b",
       "LinkEncoded": "/1/1234600/1/Bitmap-Bureau?map=c,c,b,b",
       "Map": "b",
       "Value": "Bitmap-Bureau"
     },
      {
        "Quantity": 1,
        "Position": null,
        "Name": "Sega",
        "Link": "/1/1234600/1/Sega?map=c,c,b,b",
        "LinkEncoded": "/1/1234600/1/Sega?map=c,c,b,b",
        "Map": "b",
        "Value": "Sega"
      },
      {
        "Quantity": 3,
        "Position": null,
        "Name": "Technogym",
        "Link": "/1/1234600/1/Technogym?map=c,c,b,b",
        "LinkEncoded": "/1/1234600/1/Technogym?map=c,c,b,b",
        "Map": "b",
        "Value": "Technogym"
      },
      {
        "Quantity": 3,
        "Position": null,
        "Name": "Aptany",
        "Link": "/1/1234600/1/Aptany?map=c,c,b,b",
        "LinkEncoded": "/1/1234600/1/Aptany?map=c,c,b,b",
        "Map": "b",
        "Value": "Aptany"
      },
      {
        "Quantity": 1,
        "Position": null,
        "Name": "Tectoy",
        "Link": "/1/1234600/1/Tectoy?map=c,c,b,b",
        "LinkEncoded": "/1/1234600/1/Tectoy?map=c,c,b,b",
        "Map": "b",
        "Value": "Tectoy"
      }
    ],
      "SpecificationFilters": {},
        "CategoriesTrees": [
          {
            "Id": 1,
            "Quantity": 4,
            "Position": null,
            "Name": "Beers Beers Mesmo",
            "Link": "/Beers-Beers-Mesmo/1?map=c,b",
            "LinkEncoded": "/Beers-Beers-Mesmo/1?map=c,b",
            "Map": "c",
            "Value": "Beers-Beers-Mesmo",
            "Children": [
              {
                "Id": 2,
                "Quantity": 1,
                "Position": null,
                "Name": "Lager Beers",
                "Link": "/Beers-Beers-Mesmo/Lager-Beers/1?map=c,c,b",
                "LinkEncoded": "/Beers-Beers-Mesmo/Lager-Beers/1?map=c,c,b",
                "Map": "c",
                "Value": "Lager-Beers",
                "Children": []
              }
            ]
          },
          {
            "Id": 1234571,
            "Quantity": 2,
            "Position": null,
            "Name": "Jogos",
            "Link": "/Jogos/1?map=c,b",
            "LinkEncoded": "/Jogos/1?map=c,b",
            "Map": "c",
            "Value": "Jogos",
            "Children": []
          },
          {
            "Id": 1234579,
            "Quantity": 3,
            "Position": null,
            "Name": "189",
            "Link": "/189/1?map=c,b",
            "LinkEncoded": "/189/1?map=c,b",
            "Map": "c",
            "Value": "189",
            "Children": []
          },
          {
            "Id": 1234587,
            "Quantity": 1,
            "Position": null,
            "Name": "Tests",
            "Link": "/Tests/1?map=c,b",
            "LinkEncoded": "/Tests/1?map=c,b",
            "Map": "c",
            "Value": "Tests",
            "Children": []
          },
          {
            "Id": 1234595,
            "Quantity": 1,
            "Position": null,
            "Name": "Accessories",
            "Link": "/Accessories/1?map=c,b",
            "LinkEncoded": "/Accessories/1?map=c,b",
            "Map": "c",
            "Value": "Accessories",
            "Children": [
              {
                "Id": 1234596,
                "Quantity": 1,
                "Position": null,
                "Name": "Foam rollers",
                "Link": "/Accessories/Foam-rollers/1?map=c,c,b",
                "LinkEncoded": "/Accessories/Foam-rollers/1?map=c,c,b",
                "Map": "c",
                "Value": "Foam-rollers",
                "Children": []
              }
            ]
          },
          {
            "Id": 1234597,
            "Quantity": 2,
            "Position": null,
            "Name": "Bars",
            "Link": "/Bars/1?map=c,b",
            "LinkEncoded": "/Bars/1?map=c,b",
            "Map": "c",
            "Value": "Bars",
            "Children": [
              {
                "Id": 1234598,
                "Quantity": 1,
                "Position": null,
                "Name": "Training Bars",
                "Link": "/Bars/Training-Bars/1?map=c,c,b",
                "LinkEncoded": "/Bars/Training-Bars/1?map=c,c,b",
                "Map": "c",
                "Value": "Training-Bars",
                "Children": []
              },
              {
                "Id": 1234599,
                "Quantity": 1,
                "Position": null,
                "Name": "Curl Bars",
                "Link": "/Bars/Curl-Bars/1?map=c,c,b",
                "LinkEncoded": "/Bars/Curl-Bars/1?map=c,c,b",
                "Map": "c",
                "Value": "Curl-Bars",
                "Children": []
              }
            ]
          },
          {
            "Id": 15,
            "Quantity": 1,
            "Position": null,
            "Name": "Coronas",
            "Link": "/Coronas/1?map=c,b",
            "LinkEncoded": "/Coronas/1?map=c,b",
            "Map": "c",
            "Value": "Coronas",
            "Children": [
              {
                "Id": 13,
                "Quantity": 1,
                "Position": null,
                "Name": "não tem limite!",
                "Link": "/Coronas/nao-tem-limite-/1?map=c,c,b",
                "LinkEncoded": "/Coronas/nao-tem-limite-/1?map=c,c,b",
                "Map": "c",
                "Value": "nao-tem-limite-",
                "Children": []
              }
            ]
          },
          {
            "Id": 4,
            "Quantity": 4,
            "Position": null,
            "Name": "Merch Integration Category ||",
            "Link": "/Merch-Integration-Category-||/1?map=c,b",
            "LinkEncoded": "/Merch-Integration-Category-%7C%7C/1?map=c,b",
            "Map": "c",
            "Value": "Merch-Integration-Category-||",
            "Children": []
          }
        ],
          "PriceRanges": [],
            "Summary": {
              "Departments": {
                "DisplayedItems": 8,
                  "TotalItems": 8
              },
                "CategoriesTrees": {
                  "DisplayedItems": 13,
                    "TotalItems": 13
                },
                  "Brands": {
                    "DisplayedItems": 10,
                      "TotalItems": 10
                  },
                    "PriceRanges": {
                      "DisplayedItems": 0,
                        "TotalItems": 0
                    },
                      "SpecificationFilters": {}
            }
}
``` """,
    tags=['category_facet_retrieval', 'product_searching', 'advanced_product_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def facetscategory(
    map: str,
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    term: str = ...,
    field_from: Optional[str] = Query(None, alias='_from'),
    field_to: Optional[str] = Query(None, alias='_to'),
):
    """
    Search by Store Facets
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/accessories/{productId}',
    description=""" Retrieves general information about the product's accessories. """,
    tags=['product_searching'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_accessories(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: int = Path(..., alias='productId'),
):
    """
    Get Product Search of Accessories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/showtogether/{productId}',
    description=""" Retrieves general information about the products that are show together with the product in question. """,
    tags=['product_searching', 'advanced_product_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_show_together(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: int = Path(..., alias='productId'),
):
    """
    Get Product Search of Show Together
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/similars/{productId}',
    description=""" Retrieves general information about related product searches. """,
    tags=['product_searching', 'related_product_recommendations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_similars(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: int = Path(..., alias='productId'),
):
    """
    Get Product Search of Similars
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/suggestions/{productId}',
    description=""" Retrieves general information about other product suggestions related to the product. """,
    tags=['product_searching', 'product_search_autocomplete'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_suggestions(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: int = Path(..., alias='productId'),
):
    """
    Get Product Search of Suggestions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/whoboughtalsobought/{productId}',
    description=""" Retrieves general information about other related products that the user also bought. """,
    tags=['product_searching', 'related_product_recommendations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_who_bought_also_bought(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: str = Path(..., alias='productId'),
):
    """
    Get Product Search of Who Bought Also Bought
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/whosawalsobought/{productId}',
    description=""" Retrieves general information about other related products that the users saw and also bought. """,
    tags=['product_searching', 'related_product_recommendations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_who_saw_also_bought(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: str = Path(..., alias='productId'),
):
    """
    Get Product Search of Who Saw Also Bought
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/crossselling/whosawalsosaw/{productId}',
    description=""" Retrieves general information about other related products that the users also saw. """,
    tags=['product_searching', 'related_product_recommendations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_who_saw_also_saw(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: int = Path(..., alias='productId'),
):
    """
    Get Product Search of Who Saw Also Saw
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/offers/{productId}',
    description=""" Retrieves existing offers of a specific product. """,
    tags=['product_searching', 'product_offer_lookup'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def get_api_catalog_system_pub_products_offers__product_id(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: str = Path(..., alias='productId'),
):
    """
    Search Product offers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/offers/{productId}/sku/{skuId}',
    description=""" Retrieves existing offers of a specific SKU. """,
    tags=['product_offer_lookup', 'product_searching'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def search_sku_offers(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_id: str = Path(..., alias='productId'),
    sku_id: str = Path(..., alias='skuId'),
):
    """
    Search SKU offers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/search',
    description=""" Retrieves general information about the store products. This information can be filtered and ordered by a number of options. It also can be paginated, filtered and ordered. 

## Filters  

- **Filter by full text** - `ft={searchWord}`  
E.g.: `ft=television`

- **Filter by category** - `fq=C:/{a}/{b}`  
`{a}` and `{b}` are Category IDs   
E.g.: `fq=C:/1000041/1000049/`

- **Filter by brand** - `fq=B:/{a}/{b}`  
`{a}` and `{b}` are Brand IDs
E.g.: `fq=B:/189385/189387/`

- **Filter by specification** - `fq=specificationFilter_{a}:{b}`  
`{a}` is the specification ID
`{b}` is the specification value
E.g.: To filter products where the color is Blue, find the specification ID for color. Suppose it is 123, then the query will be: `fq=specificationFilter_123:Blue`

- **Filter by price range** - `fq=P:[{a} TO {b}]`  
`{a}`  is the minimum price "from"
`{b}` is the highest price "to"  
E.g.: `fq=P:[0 TO 20]` will search products between 0.00 and 20.00.  

- **Filter by collection** - `fq=productClusterIds:{{productClusterId}}` 
`productClusterId` is the same as `collectionId`  
For more information about collections, read [Creating a product collection](https://help.vtex.com/en/tutorial/creating-a-product-collection).

- **Filter by product ID** - `fq=productId:{{productId}}`

- **Filter by SKU ID** - `fq=skuId:{{skuId}}`

- **Filter by referenceId** - `fq=alternateIds_RefId:{{referenceId}}`

- **Filter by EAN13** - `fq=alternateIds_Ean:{{ean13}}`

- **Filter by availability at a specific sales channel** - `fq=isAvailablePerSalesChannel_{{sc}}:{{bool}}`  
`{{sc}}` is the desired sales channel  
`{{bool}}` is true ou false, 1 or 0.  
E.g.: seaching available products for the sales channel 4 would be `fq=isAvailablePerSalesChannel_4:1`

- **Filter by available at a specific seller** - `fq=sellerId:{{sellerId}}`
The search does not include White Label Sellers.

## Pagination

- **Initial item number** - `_from={{first}}`
- **Final item number** - `_to={{last}}`

>⚠️ This endpoint returns a maximum of 50 items per response, so the difference between `_from` and `_to` should not exceed this number. The result order is descending, from the highest product ID to the lowest.

## Sorting

- **Price**  
`O=OrderByPriceDESC`  
`O=OrderByPriceASC`

- **Top Selling Products**  
`O=OrderByTopSaleDESC`

- **Best Reviews**  
`O=OrderByReviewRateDESC`

- **Name**  
`O=OrderByNameASC`  
`O=OrderByNameDESC`

- **Release Date**  
`O=OrderByReleaseDateDESC`

- **Best Discounts**  
`O=OrderByBestDiscountDESC`

- **Score**  
`O=OrderByScoreDESC` """,
    tags=['product_searching', 'advanced_product_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search_filteredand_ordered(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    field_from: Optional[str] = Query(None, alias='_from'),
    field_to: Optional[str] = Query(None, alias='_to'),
    ft: Optional[str] = None,
    fq: Optional[str] = None,
    o: Optional[str] = Query(None, alias='O'),
):
    """
    Search for Products with Filter, Order and Pagination
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/search/{product-text-link}/p',
    description=""" Retrieves general information about the product of the URL you searched for. """,
    tags=['product_searching', 'direct_url_product_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def searchbyproducturl(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    product_text_link: str = Path(..., alias='product-text-link'),
):
    """
    Search Product by Product URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/catalog_system/pub/products/search/{search}',
    description=""" Retrieves general information about the products related to the term searched. 
This is the main search used by the store. The user can type anything to be searched.  

For example, if they search for a "decanter", this is the URL: `https://{{accountName}}.{{environment}}.com.br/api/catalog_system/pub/products/search/decanter`. 

Note that maybe the response can be HTTP 200 or 206, 206 means that it's a partial content response.

If it is a 206 take a look at the Headers, will be an entry called resources. E.g.: resources → 0-9/19. This means that the response is showing items from 0 to 9, 10 items, but there were 19 items found. See more information at the paging route example. """,
    tags=['product_searching', 'advanced_product_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def product_search(
    accept: str = Header(..., alias='Accept'),
    content__type: str = Header(..., alias='Content-Type'),
    search: str = ...,
):
    """
    Search for Products
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/buscaautocomplete',
    description=""" Retrieves product's information related to the searched string.
`{{searchString}} is the part of string the user is looking for.
E.g.: `ref` | `refrig` | `refrigerator` """,
    tags=['product_searching', 'product_search_autocomplete'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def auto_complete(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    product_name_contains: str = Query(..., alias='productNameContains'),
):
    """
    Product Search Autocomplete
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
